# Tox (http://tox.testrun.org/) is a tool for running tests
# in multiple virtualenvs. This configuration file will run the
# test suite on all supported python versions. To use it, "pip install tox"
# and then run "tox" from this directory.

[tox]
requires =
    sphinx-scrapy @ git+https://github.com/scrapy/sphinx-scrapy.git@999017c29b8bc213843e86e0e350a85c47493e34
# pypy3 excluded due to https://github.com/kevin1024/vcrpy/issues/885
envlist = py{39,310,311,312}-{json,msgpack},docs

[testenv]
deps =
    -r tests/requirements.txt
    msgpack: -r tests/requirements-msgpack.txt
commands = py.test --cov=scrapinghub --cov-report=xml {posargs: scrapinghub tests}

